

name: change


# Manual trigger with parameters
on:
  workflow_dispatch:
    inputs:
      # This is the path of your notebooks in Git.  Currently, this is not recursively deploying notebooks
      
      GIT_NOTEBOOK_PATH:
        description: 'Notebooks Relative Path in Git'
        required: true
        default: 'testcommit'

      GIT_URL:
        description: 'Repo URL'
        required: true
        default: 'https://github.com/kritktongrakroj/SCB.git'


      INPUT_TAG:
        description: 'Tag name or baseline name'
        required: true
        default: 'BSL003'

      BRANCH:
        description: 'Branch name'
        required: true
        default: 'RELEASEID001'


jobs:
  #############################################################
  # Builds the code
  # Currently this is not building and JAR files, but you would do that here
  # This is packaging up the files from Git to the Artifacts files
  #############################################################
  Build:
    runs-on: ubuntu-latest
    env:
       temp_repo_path: '${{ github.workspace }}/clonrepo'
       repo_url: '${{ github.event.inputs.GIT_URL }}'
       input_tag: '${{ github.event.inputs.INPUT_TAG }}'
       notebookpath: '${{ github.workspace }}/${{ github.event.inputs.GIT_NOTEBOOK_PATH }}'
       branch_name: '${{ github.event.inputs.BRANCH }}'
      
    # Checkout code
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 #install the python needed
      
    - name: Install dependencies
      run: |
        cd "$GITHUB_WORKSPACE/Deployment-Scripts/rollback"
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      
    - name: Deploy script1
      run: |
       chmod +x $GITHUB_WORKSPACE/Deployment-Scripts/rollback/deploy-rollback.py
       python3 $GITHUB_WORKSPACE/Deployment-Scripts/rollback/deploy-rollback.py ${{ env.input_tag }} ${{ env.repo_url }} ${{ env.temp_repo_path }} ${{ env.notebookpath }} ${{ env.branch_name }}
      

    # Publish Artifact: Deployment-Scripts
    - name: 'Publish Artifact: Deployment-Scripts' 
      uses: actions/upload-artifact@v2
      with:
        name: 'deployment-scripts'
        path: '${{ github.workspace }}/Deployment-Scripts/rollback'
    
   
#############################################################
# Deploy to Dev
#############################################################
  Dev:
    needs: Build
    runs-on: ubuntu-latest
    env:
       repopath: '${{ github.workspace }}/clonrepo'
       repourl: '${{ github.event.inputs.GIT_URL }}'
       inputtag: '${{ github.event.inputs.INPUT_TAG }}'

    steps:

    - name: Checkout code
      uses: actions/checkout@v2
    
    # Download Artifact: Deployment Scripts
    - name: 'Download Artifact: Deployment Scripts' 
      uses: actions/download-artifact@v2
      with:
        name: 'deployment-scripts'
        path: ${{ github.workspace }}/Deployment-Scripts/rollback

    

    