name: DataBricks-Deployment-Tag-CICD


# Manual trigger with parameters
on:
  workflow_dispatch:
    inputs:
      # This is the path of your notebooks in Git.  Currently, this is not recursively deploying notebooks
      GIT_NOTEBOOK_PATH:
        description: 'Notebooks Relative Path in Git'
        required: true
        default: 'notebooks/'

      # This is where in your Databricks workspace your notebooks will be deployed
      # Typically this is under a Folder under the Workspace and not under a specific user's folder
      NOTEBOOK_DEPLOYMENT_PATH:
        description: 'Notebooks Deployment Path to Databricks'
        required: true
        default: '/DPDEV'

      # This resource group for the Databricks workspace and KeyVault
      RESOURCE_GROUP:
        description: 'Resource Group Name'
        required: true
        default: 'devops-gitenterprise-adb'

      # This is the name of your Azure Databricks resource
      WORKSPACE_NAME:
        description: 'Databricks workspace name'
        required: true
        default: 'devops-demo-adb'

      # This is a KeyVault for holding the Service Principal to make Databricks API calls and to hold Databricks KeyVault backed Secrets
      SUBSCRIPTION_ID:
        description: 'Azure Subscription Id'
        required: true
        default: '2546a5d7-a653-480f-a60a-a043b9a6f7b3'
      
      CLUSTER_NAME:
        description: 'Name of Azure Databricks Cluster'
        required: true
        default: 'test-cluster'

      MODE:
        description: 'Deployment Mode (Databricks or Initialize-KeyVault)'
        required: true
        default: 'Databricks'
      
      BASELINE:
        description: 'Baseline or Tag Name'
        required: true
        default: 'BSL001'
      
        

jobs:
  #############################################################
  # Builds the code
  # Currently this is not building and JAR files, but you would do that here
  # This is packaging up the files from Git to the Artifacts files
  #############################################################
  Build:
    runs-on: ubuntu-latest
      
    # Checkout code
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
     
      
    # Publish Artifact: Databricks-Notebooks
    - name: 'Publish Artifact: Databricks-Notebooks' 
      uses: actions/upload-artifact@v2
      with:
        name: 'notebooks'
        path: '${{ github.workspace }}/${{ github.event.inputs.GIT_NOTEBOOK_PATH }}'

    # Publish Artifact: Databricks-Deployment-Scripts
    - name: 'Publish Artifact: Databricks-Deployment-Scripts' 
      uses: actions/upload-artifact@v2
      with:
        name: 'deployment-scripts'
        path: '${{ github.workspace }}/Deployment-Scripts/AzureDatabricks'
    
   
#############################################################
# Deploy to Dev
#############################################################
  Dev:
    needs: Build
    runs-on: ubuntu-latest

    env:
      resourceGroupName: '${{ github.event.inputs.RESOURCE_GROUP }}'
      GITNB: '${{ github.event.inputs.GIT_NOTEBOOK_PATH }}'
      databricksWorkspaceName: '${{ github.event.inputs.WORKSPACE_NAME }}'
      NOTEBOOK_EXE_PATH: '${{ github.event.inputs.NOTEBOOK_DEPLOYMENT_PATH }}/streaming/fw/init/run_init'
      baseline: '${{ github.event.inputs.BASELINE }}'
      MENV_RLT: 'dpdev'
      MENV_BT: 'dpdev'
      SECRET_SCOPT_RLT: dataplatformscope
      SECRET_SCOPT_BT: dataplatformscope
      CLUSTER_ID_RLT: 0112-111315-surer122
      CLUSTER_ID_BT: 0112-111315-surer122
  
    steps:

    # Download Artifact: Databricks-Notebooks
    - name: 'Download Artifact: Databricks-Notebooks' 
      uses: actions/download-artifact@v2
      with:
        name: 'notebooks'
        path: ${{ github.workspace }}/${{ github.event.inputs.GIT_NOTEBOOK_PATH }}

    # Download Artifact: Deployment Scripts
    - name: 'Download Artifact: Deployment Scripts' 
      uses: actions/download-artifact@v2
      with:
        name: 'deployment-scripts'
        path: ${{ github.workspace }}/Deployment-Scripts/AzureDatabricks

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 #install the python needed
    - name: Install dependencies
      run: |
        cd "$GITHUB_WORKSPACE/Deployment-Scripts/AzureDatabricks"
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
     # Replace Environment Real time
    - name: 'Replace Environment Real time' 
      run: |
        echo "replacing env vars from GitHub Action"
        cd "$GITHUB_WORKSPACE/$GITNB/streaming/fw/cmmn/config"
        ls
        set -e
        envsubst < environment_config_template.py > environment_config.py
        head environment_config.py
        
     # Replace Environment batch
    - name: 'Replace Environment Batch' 
      run: |
        echo "replacing env vars from GitHub Action"
        cd "$GITHUB_WORKSPACE/$GITNB/batch/fw/cmmn/config"
        ls
        set -e
        envsubst < environment_config_template.py > environment_config.py
        head environment_config.py
        
    - name: Deploy Databricks Notebooks
      run: |
       chmod +x $GITHUB_WORKSPACE/Deployment-Scripts/AzureDatabricks/deploy-notebooks.py
       python3 $GITHUB_WORKSPACE/Deployment-Scripts/AzureDatabricks/deploy-notebooks.py ${{ secrets.dev_tenant_id }} ${{ secrets.dev_client_id }} ${{ secrets.dev_client_secret }} ${{ secrets.dev_subscription_id }} ${{ env.resourceGroupName }} ${{ env.databricksWorkspaceName }} ${{ github.event.inputs.NOTEBOOK_DEPLOYMENT_PATH }} ${{ github.event.inputs.GIT_NOTEBOOK_PATH }}
