name: import-jar

on:
  workflow_dispatch:
    

jobs:
  #############################################################
  # Builds the code
  # Currently this is not building and JAR files, but you would do that here
  # This is packaging up the files from Git to the Artifacts files
  #############################################################
  Build:
    runs-on: ubuntu-latest 
    env:
      keyvaultname: 'devopstestadb-kv'   
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    
    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.ACN_SP_DEV }}
        
        
    - name: Azure Key Vault Action
      uses: Azure/get-keyvault-secrets@v1
      with:
        keyvault: ${{ env.keyvaultname }}
        secrets: 'client-id,client-secret,subscriptionId,tenantId'
