# This is a basic workflow to help you get started with Actions

name: oneclick

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      # This is the path of your notebooks in Git.  Currently, this is not recursively deploying notebooks
      Excel_Path:
        description: 'Execel Relative Path'
        required: true
        default: 'DataX_CardX_BSL_0005_Deployment_Steps_v00.00.04.xlsx'
        
      Date:
        description: 'Date in format 25052022 to specify folder'
        required: true
        default: '24052022'

      # This is the path of your notebooks in Git.  Currently, this is not recursively deploying notebooks
      Env:
        description: 'Monoline Environment (npr,prp,prd)'
        required: true
        default: 'npr'
        

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  #############################################################
  # Builds the code
  # Currently this is not building and JAR files, but you would do that here
  # This is packaging up the files from Git to the Artifacts files
  #############################################################
  # This workflow contains a single job called "build"
  Build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env: 
      pat_token: ${{ secrets.PAT_TOKEN_1 }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      ############# Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it ############################
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
         python-version: 3.8 #install the python needed
                
               # Publish Artifact: Deployment-Scripts
      - name: 'Publish Artifact: Deployment-Scripts'
        uses: actions/upload-artifact@v2
        with:
          name: 'deployment-scripts'
          path: '${{ github.workspace }}/Deployment-Scripts/oneclick'                      

      
 
 #############################################################
# Deploy to PRD
#############################################################
  PRD:
    needs: Build
    runs-on: ubuntu-latest
    env: 
      pat_token: ${{ secrets.PAT_TOKEN_1 }}
      repo_name: 'SCB'
      repo_owner: 'kritktongrakroj'
      
    steps:
        
        ############### Checkout Excel deployment repo ###############################
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          repository: 'kritktongrakroj/datax-excel-dp'
          token: ${{ env.pat_token }}
        
        # Download Artifact: Deployment Scripts
      - name: 'Download Artifact: Deployment Scripts'  
        uses: actions/download-artifact@v2
        with:
          name: 'deployment-scripts'
          path: ${{ github.workspace }}/Deployment-Scripts/oneclick
          
      - name: Install dependencies
        run: |
           cd "$GITHUB_WORKSPACE/Deployment-Scripts/oneclick"
           python -m pip install --upgrade pip
           pip install -r requirements.txt
        
      - name: Run the One-click 
        run: |
         cd "$GITHUB_WORKSPACE/Deployment-Scripts/oneclick"
         python3 $GITHUB_WORKSPACE/Deployment-Scripts/oneclick/oneclickdeployment.py ${{ github.workspace }}/${{ github.event.inputs.Date}}/${{ github.event.inputs.Excel_Path}} ${{ env.pat_token }}  ${{ env.repo_owner }}  ${{ env.repo_name }}
    
      - name: Run the One-click 
        run: |
         cd "$GITHUB_WORKSPACE/Deployment-Scripts/oneclick"
         python3 $GITHUB_WORKSPACE/Deployment-Scripts/oneclick/excel-deploy-adb.py ${{ github.workspace }}/${{ github.event.inputs.Date}}/${{ github.event.inputs.Excel_Path}} ${{ env.pat_token }}  ${{ env.repo_owner }}  ${{ env.repo_name }}
    
