name: Test-CommitID-Dev


# Manual trigger with parameters
on:
  workflow_dispatch:
    inputs:
      

      # This resource group for the Databricks workspace and KeyVault
      RESOURCE_GROUP:
        description: 'Resource Group Name'
        required: true
        default: 'Devopsdeploy-cosmos-dev-poc'


      # This is a KeyVault for holding the Service Principal to make Databricks API calls and to hold Databricks KeyVault backed Secrets
      KEY_VAULT_NAME:
        description: 'KeyVault name'
        required: true
        default: 'devops-key-dev'


jobs:
  #############################################################
  # Builds the code
  # Currently this is not building and JAR files, but you would do that here
  # This is packaging up the files from Git to the Artifacts files
  #############################################################
  Build:
    runs-on: ubuntu-latest

    # Checkout code
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    
    
                   


#############################################################
# Deploy to Dev
#############################################################
  Dev:
    needs: Build
    runs-on: ubuntu-latest
    env:
      resourceGroupName: '${{ github.event.inputs.RESOURCE_GROUP }}'
      keyVaultName: '${{ github.event.inputs.KEY_VAULT_NAME }}'

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
        
    # Login to Azure
    - name: Login via Az module
      uses: ./Marketplace-Module/azure-login
      with:
        creds: ${{ secrets.DEV_AZURE_CREDENTIALS }}
        # set this if you will be using PowerShell
        # enable-AzPSSession: true 
    
    # Download KeyVault Secrets
    - name: Download KeyVault Secrets
      uses: ./Marketplace-Module/keyvault-module
      with:
        keyvault: ${{ env.keyVaultName }}
        secrets: 'keyvault-client-id,keyvault-client-secret,keyvault-tenant-id,keyvault-subscription-id'
      id: myGetSecretAction
