name: Test-CommitID-Dev


# Manual trigger with parameters
on:
  workflow_dispatch:
    inputs:
      # This to test notebook path
      GIT_NOTEBOOK_PATH:
        description: 'Notebooks Relative Path in Git'
        required: true
        default: 'testcommit/'
        

      # This is commit id value
      COMMIT_ID:
        description: 'Commit ID'
        required: true
        default: '1e184eba51c7b408bdc7924498446e52e91b5aa7'

      # This is commit id value
      BASELINE_ID:
        description: 'Baseline ID'
        required: true
        default: 'BSL..'

jobs:
  #############################################################
  # Builds the code
  # Currently this is not building and JAR files, but you would do that here
  # This is packaging up the files from Git to the Artifacts files
  #############################################################
  Build:
    runs-on: ubuntu-latest

    # Checkout code
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # upload file: test file
    - name: 'test upload past-version file' 
      uses: actions/upload-artifact@v2
      with:
        path: '${{ github.workspace }}/${{ github.event.inputs.GIT_NOTEBOOK_PATH }}'
    
                   
